
[project]
name = "mcp-askllm"
version = "0.1.0"
description = "An MCP server to ask LLMs"
requires-python = ">=3.8"
dependencies = [
    "fastmcp",
    "litellm",
    "pyyaml",
    "python-dotenv",
]

[project.scripts]
mcp-askllm = "server:main"

[tool.setuptools]
py-modules = ["server"]
